# Generated by Django 5.1.1 on 2024-09-11 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('former', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='practice',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='practice',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studygroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='practicepole',
            name='pole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='former.pole', verbose_name='Поле'),
        ),
        migrations.AddField(
            model_name='practicepole',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='former.practice', verbose_name='Практика'),
        ),
        migrations.AddField(
            model_name='userpractice',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='former.practice', verbose_name='Практика'),
        ),
        migrations.AddField(
            model_name='userpractice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
