# Generated by Django 5.1.1 on 2024-09-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('former', '0003_alter_practice_additional_alter_practice_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='type',
            field=models.IntegerField(choices=[(0, 'SYSTEM'), (1, 'CUSTOM')], default=1),
        ),
        migrations.AddField(
            model_name='practice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
