# Generated by Django 5.1.1 on 2024-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('former', '0004_pole_type_practice_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicepole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpractice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
