# Generated by Django 5.1.1 on 2024-09-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('former', '0005_practicepole_is_active_userpractice_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpractice',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
