# Generated by Django 5.1.1 on 2024-09-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studygroup_is_active_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='surname', max_length=20, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
